name: book_my_seat
description: Flutter package to create seat booking layout in Flutter.
version: 1.0.0
homepage: https://github.com/SharmaPrateek196/book_my_seat

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_svg: ^1.0.2

dev_dependencies:

flutter: